# Generated by Django 3.2.4 on 2021-06-20 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20210618_2007'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
